version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/demo_db'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: postgres
      POSTGRES_DB: student
      PGUSER: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
